# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directories:
      - "/"
      - "/core-api/"
      - "/django_app/"
      - "/redbox-core/"
      - "/worker/"
    schedule:
      interval: "daily"
    groups:
      minor-patch:
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: faststream
      - dependency-name: torch # https://dev-discuss.pytorch.org/t/pytorch-macos-x86-builds-deprecation-starting-january-2024/1690
      - dependency-name: sentence-transformers
      - dependency-name: pikepdf
