# Generated by Django 4.2.10 on 2024-02-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("redbox_core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="invite_accepted_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="invited_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="last_token_sent_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="verified",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
