# Generated by Django 5.0.6 on 2024-05-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("redbox_core", "0003_chathistory_file_chatmessage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="password"
            ),
        ),
    ]
