# Generated by Django 4.2.11 on 2024-03-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0003_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.TextField(help_text='location of file'),
        ),
    ]
