# Generated by Django 5.0.6 on 2024-05-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0005_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='core_file_uuid',
            field=models.UUIDField(null=True),
        ),
    ]
