# Generated by Django 5.0.6 on 2024-05-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0006_file_core_file_uuid_alter_file_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='core_file_uuid',
            field=models.UUIDField(),
        ),
    ]
