# Generated by Django 5.0.6 on 2024-05-21 06:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("redbox_core", "0008_alter_file_processing_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="processing_status",
        ),
    ]
