# Generated by Django 5.0.6 on 2024-05-22 14:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("redbox_core", "0009_file_expiry_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="file",
            old_name="expiry_date",
            new_name="last_referenced",
        ),
    ]
