# Generated by Django 5.0.6 on 2024-06-12 09:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


def file_to_text_chunk(apps, schema_editor):
    ChatMessage = apps.get_model("redbox_core", "ChatMessage")
    TextChunk = apps.get_model("redbox_core", "TextChunk")
    for chat_message in ChatMessage.objects.all():
        for file in chat_message.source_files.all():
            TextChunk.objects.create(
                file=file,
                chat_message=chat_message,
            )


class Migration(migrations.Migration):
    dependencies = [
        ("redbox_core", "0014_remove_chathistory_selected_files"),
    ]

    operations = [
        migrations.CreateModel(
            name="TextChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("text", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "chat_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="redbox_core.chatmessage",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="redbox_core.file",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="chunks",
            field=models.ManyToManyField(
                through="redbox_core.TextChunk", to="redbox_core.file"
            ),
        ),
        migrations.RunPython(file_to_text_chunk, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="chatmessage",
            name="source_files",
        ),
    ]
