# Generated by Django 5.0.6 on 2024-07-08 10:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0020_remove_chatmessage_source_files_textchunk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessageRating',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('chat_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='redbox_core.chatmessage')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('text', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChatMessageRatingChip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=32)),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redbox_core.chatmessagerating')),
            ],
            options={
                'abstract': False,
                'unique_together': {('rating', 'text')},
            },
        ),
    ]
