# Generated by Django 5.0.7 on 2024-07-16 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0021_chatmessagerating_chatmessageratingchip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='old_source_files',
        ),
    ]
