# Generated by Django 5.0.7 on 2024-07-18 07:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("redbox_core", "0022_remove_chatmessage_old_source_files"),
    ]

    operations = [
        migrations.AddField(
            model_name="citation",
            name="page_numbers",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(),
                blank=True,
                help_text="location of citation in document",
                null=True,
                size=None,
            ),
        ),
    ]
