# Generated by Django 5.0.7 on 2024-07-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0025_alter_file_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('parsing', 'Parsing'), ('chunking', 'Chunking'), ('embedding', 'Embedding'), ('indexing', 'Indexing'), ('complete', 'Complete'), ('unknown', 'Unknown'), ('deleted', 'Deleted'), ('errored', 'Errored'), ('processing', 'Processing'), ('failed', 'Failed')]),
        ),
    ]
