# Generated by Django 5.0.7 on 2024-08-02 10:26

from django.db import migrations, models


def update_file_status(apps, schema_editor):
    File = apps.get_model("redbox_core", "File")
    File.objects.filter(status="uploaded").update(status="processing")
    File.objects.filter(status="parsing").update(status="processing")
    File.objects.filter(status="chunking").update(status="processing")
    File.objects.filter(status="embedding").update(status="processing")
    File.objects.filter(status="indexing").update(status="processing")
    File.objects.filter(status="unknown").update(status="errored")
    File.objects.filter(status="failed").update(status="errored")


class Migration(migrations.Migration):
    dependencies = [
        ("redbox_core", "0026_alter_file_status"),
    ]

    operations = [
        migrations.RunPython(update_file_status, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="file",
            name="status",
            field=models.CharField(
                choices=[
                    ("complete", "Complete"),
                    ("deleted", "Deleted"),
                    ("errored", "Errored"),
                    ("processing", "Processing"),
                ]
            ),
        ),
    ]
