# Generated by Django 5.0.7 on 2024-08-06 10:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("redbox_core", "0027_alter_file_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="AISettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(max_length=50, unique=True)),
                ("context_window_size", models.PositiveIntegerField(default=8000)),
                ("rag_k", models.PositiveIntegerField(default=30)),
                ("rag_num_candidates", models.PositiveIntegerField(default=10)),
                ("rag_desired_chunk_size", models.PositiveIntegerField(default=300)),
                ("elbow_filter_enabled", models.BooleanField(default=False)),
                (
                    "chat_system_prompt",
                    models.TextField(
                        default="You are an AI assistant called Redbox tasked with answering questions and providing information objectively."
                    ),
                ),
                (
                    "chat_question_prompt",
                    models.TextField(default="{question}\n=========\n Response: "),
                ),
                ("stuff_chunk_context_ratio", models.FloatField(default=0.75)),
                (
                    "chat_with_docs_system_prompt",
                    models.TextField(
                        default="You are an AI assistant called Redbox tasked with answering questions on user provided documents and providing information objectively."
                    ),
                ),
                (
                    "chat_with_docs_question_prompt",
                    models.TextField(
                        default="Question: {question}. \n\n Documents: \n\n {formatted_documents} \n\n Answer: "
                    ),
                ),
                (
                    "chat_with_docs_reduce_system_prompt",
                    models.TextField(
                        default="You are an AI assistant tasked with answering questions on user provided documents. Your goal is to answer the user question based on list of summaries in a coherent manner.Please follow these guidelines while answering the question: \n1) Identify and highlight key points,\n2) Avoid repetition,\n3) Ensure the answer is easy to understand,\n4) Maintain the original context and meaning.\n"
                    ),
                ),
                (
                    "retrieval_system_prompt",
                    models.TextField(
                        default="Given the following conversation and extracted parts of a long document and a question, create a final answer. \nIf you don't know the answer, just say that you don't know. Don't try to make up an answer. If a user asks for a particular format to be returned, such as bullet points, then please use that format. If a user asks for bullet points you MUST give bullet points. If the user asks for a specific number or range of bullet points you MUST give that number of bullet points. \nUse **bold** to highlight the most question relevant parts in your response. If dealing dealing with lots of data return it in markdown table format. "
                    ),
                ),
                (
                    "retrieval_question_prompt",
                    models.TextField(
                        default="{question} \n=========\n{formatted_documents}\n=========\nFINAL ANSWER: "
                    ),
                ),
                (
                    "condense_system_prompt",
                    models.TextField(
                        default="Given the following conversation and a follow up question, generate a follow up question to be a standalone question. You are only allowed to generate one question in response. Include sources from the chat history in the standalone question created, when they are available. If you don't know the answer, just say that you don't know, don't try to make up an answer. \n"
                    ),
                ),
                (
                    "condense_question_prompt",
                    models.TextField(
                        default="{question}\n=========\n Standalone question: "
                    ),
                ),
                ("map_max_concurrency", models.PositiveIntegerField(default=128)),
                (
                    "chat_map_system_prompt",
                    models.TextField(
                        default="You are an AI assistant tasked with summarizing documents. Your goal is to extract the most important information and present it in a concise and coherent manner. Please follow these guidelines while summarizing: \n1) Identify and highlight key points,\n2) Avoid repetition,\n3) Ensure the summary is easy to understand,\n4) Maintain the original context and meaning.\n"
                    ),
                ),
                (
                    "chat_map_question_prompt",
                    models.TextField(
                        default="Question: {question}. \n Documents: \n {formatted_documents} \n\n Answer: "
                    ),
                ),
                (
                    "reduce_system_prompt",
                    models.TextField(
                        default="You are an AI assistant tasked with summarizing documents. Your goal is to write a concise summary of list of summaries from a list of summaries in a concise and coherent manner. Please follow these guidelines while summarizing: \n1) Identify and highlight key points,\n2) Avoid repetition,\n3) Ensure the summary is easy to understand,\n4) Maintain the original context and meaning.\n"
                    ),
                ),
                ("llm_max_tokens", models.PositiveIntegerField(default=1024)),
                ("match_boost", models.PositiveIntegerField(default=1)),
                ("knn_boost", models.PositiveIntegerField(default=1)),
                ("similarity_threshold", models.PositiveIntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
