# Generated by Django 5.0.7 on 2024-08-06 10:46

import django.db.models.deletion
import redbox_app.redbox_core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("redbox_core", "0028_aisettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ai_settings",
            field=models.ForeignKey(
                default=redbox_app.redbox_core.models.get_default_ai_settings,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="redbox_core.aisettings",
            ),
        ),
    ]
