# Generated by Django 5.0.7 on 2024-08-08 06:30

import django.db.models.deletion
from django.db import migrations, models


def move_rating_to_chat_message(apps, schema_editor):
    ChatMessageratingChip = apps.get_model("redbox_core", "chatmessageratingchip")
    for chip in ChatMessageratingChip.objects.all():
        chip.chat_message = chip.rating.chat_message
        chip.save()




class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0028_aisettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessageratingchip',
            name='chat_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='redbox_core.chatmessage'),
        ),
        migrations.RunPython(move_rating_to_chat_message, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='chatmessageratingchip',
            unique_together={('chat_message', 'text')},
        ),
        migrations.AlterField(
            model_name='chatmessageratingchip',
            name='chat_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redbox_core.chatmessage'),
        ),
        migrations.RemoveField(
            model_name='chatmessageratingchip',
            name='rating',
        ),

    ]
