# Generated by Django 5.0.7 on 2024-08-08 08:28

import django.contrib.postgres.fields
from django.db import migrations, models

def back_populate_rating_chips(apps, schema_editor):
    ChatMessageRatingChip = apps.get_model("redbox_core", "ChatMessageRatingChip")
    for chip in ChatMessageRatingChip.objects.all():
        chip.rating.chips = (chip.rating.chips or []) + [chip.text]
        chip.rating.save()


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0029_rename_chathistory_chat_alter_chat_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessagerating',
            name='chips',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, null=True, size=None),
        ),
        migrations.RunPython(back_populate_rating_chips, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='ChatMessageRatingChip',
        ),

    ]
