# Generated by Django 5.0.7 on 2024-08-08 06:39

import django.core.validators
from django.db import migrations, models


def move_chat_message_rating_fields_to_chat_message(apps, schema_editor):
    ChatMessageRating = apps.get_model("redbox_core", "chatmessagerating")
    for cmr in ChatMessageRating.objects.all():
        cmr.chat_message.rating = cmr.rating
        cmr.chat_message.rating_text = cmr.text
        cmr.chat_message.save()


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0029_chatmessageratingchip_chat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='rating',
            field=models.PositiveIntegerField(blank=True, help_text='optional user rating', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='rating_text',
            field=models.TextField(blank=True, help_text='optional user rating text', null=True),
        ),
        migrations.RunPython(move_chat_message_rating_fields_to_chat_message, migrations.RunPython.noop),

    ]
