# Generated by Django 5.0.7 on 2024-08-08 10:01

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models

def back_populate_ratings(apps, schema_editor):
    ChatMessageRating = apps.get_model("redbox_core", "ChatMessageRating")
    for cmr in ChatMessageRating.objects.all():
        cmr.chat_message.rating = cmr.rating
        cmr.chat_message.rating_text = cmr.text
        cmr.chat_message.rating_chips = cmr.chips
        cmr.chat_message.save()


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0030_chatmessagerating_chips'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='rating_chips',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='rating_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunPython(back_populate_ratings, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='ChatMessageRating',
        ),

    ]
