# Generated by Django 5.0.7 on 2024-08-08 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0032_user_new_business_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='users',
            new_name='user',
        ),
    ]
