# Generated by Django 5.1 on 2024-08-13 13:52

from django.db import migrations, models


def back_populate_ai_settings_chat_backend(apps, schema_editor):
    AISettings = apps.get_model("redbox_core", "AISettings")
    for ai_settings in AISettings.objects.all():
        ai_settings.chat_backend = "azure/gpt-4"
        ai_settings.save()


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0034_user_is_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='chat_backend',
            field=models.CharField(blank=True, choices=[('azure/gpt-35-turbo-16k', 'azure/gpt-35-turbo-16k'), ('azure/gpt-4', 'azure/gpt-4'), ('azure/gpt-4o', 'azure/gpt-4o')], help_text='LLM to use in chat', max_length=64, null=True),
        ),
        migrations.RunPython(back_populate_ai_settings_chat_backend, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='aisettings',
            name='chat_backend',
            field=models.CharField(
                choices=[('azure/gpt-35-turbo-16k', 'azure/gpt-35-turbo-16k'), ('azure/gpt-4', 'azure/gpt-4'),
                         ('azure/gpt-4o', 'azure/gpt-4o')], help_text='LLM to use in chat', max_length=64),
        ),

    ]
