# Generated by Django 5.1 on 2024-08-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0036_alter_user_business_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='max_document_tokens',
            field=models.PositiveIntegerField(default=1000000),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='context_window_size',
            field=models.PositiveIntegerField(default=128000),
        ),
    ]
