# Generated by Django 5.1 on 2024-08-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0036_alter_user_business_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_developer',
            field=models.BooleanField(blank=True, default=False, help_text='is this user a developer?', null=True),
        ),
    ]
