# Generated by Django 5.1 on 2024-08-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0038_aisettings_max_document_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_backend',
            field=models.CharField(blank=True, choices=[('gpt-35-turbo-16k', 'gpt-35-turbo-16k'), ('gpt-4-turbo-2024-04-09', 'gpt-4-turbo-2024-04-09'), ('gpt-4o', 'gpt-4o')], help_text='LLM to use in chat', max_length=64, null=True),
        ),
    ]
