# Generated by Django 5.1 on 2024-08-24 15:28

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0038_aisettings_max_document_tokens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='original_file',
            field=models.FileField(storage=storages.backends.s3.S3Storage, unique=True, upload_to=''),
        ),
    ]
