# Generated by Django 5.1.1 on 2024-09-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0042_chat_chat_backend_chat_chat_map_question_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='feedback_achieved',
            field=models.BooleanField(blank=True, help_text='Did Redbox do what you needed it to in this chat?', null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='feedback_improved_work',
            field=models.BooleanField(blank=True, help_text='Did Redbox help to improve your work?', null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='feedback_notes',
            field=models.TextField(blank=True, help_text='Do you want to tell us anything further?', null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='feedback_saved_time',
            field=models.BooleanField(blank=True, help_text='Did Redbox help save you time?', null=True),
        ),
    ]
