# Generated by Django 5.1.1 on 2024-09-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "redbox_core",
            "0042_chat_chat_backend_chat_chat_map_question_prompt_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="awaiting_llm_response",
            field=models.BooleanField(default=False),
        ),
    ]
