# Generated by Django 5.1.1 on 2024-09-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0044_aisettings_rag_gauss_scale_decay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
