# Generated by Django 5.1.1 on 2024-10-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0045_user_info_about_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='agentic_retrieval_question_prompt',
            field=models.TextField(default='Question: {question}. \n\n Documents: \n\n {formatted_documents} \n\n Answer: '),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='agentic_retrieval_system_prompt',
            field=models.TextField(default="You are a researcher whose job is to search through files a user has uploaded and then answer their question. You can use tools to search the user's uploaded files to return documents containing snippets of text to help you write the answer the user wants. If you need to, break down the question into multiple smaller questions. Create as many queries as you like to answer the question. Using the following conversation and document snippets, your tasks are: \n\n\t 1. If the document snippets do not answer the question, use tools to find snippets that do. \n\t 2. If the documents can answer the question, answer the question. \n\n"),
        ),
    ]
