# Generated by Django 5.1.1 on 2024-10-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0045_user_info_about_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='archived',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
