# Generated by Django 5.1.1 on 2024-10-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0046_chat_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='archived',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
