# Generated by Django 5.1.2 on 2024-10-10 09:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("redbox_core", "0046_chat_archived"),
    ]

    operations = [
        migrations.CreateModel(
            name="MLModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("gpt-35-turbo-16k", "gpt-35-turbo-16k"),
                            ("gpt-4-turbo-2024-04-09", "gpt-4-turbo-2024-04-09"),
                            ("gpt-4o", "gpt-4o"),
                            ("gpt-4o-mini", "gpt-4o-mini"),
                            (
                                "anthropic.claude-3-sonnet-20240229-v1:0",
                                "claude-3-sonnet",
                            ),
                            (
                                "anthropic.claude-3-haiku-20240307-v1:0",
                                "claude-3-haiku",
                            ),
                            ("llama3.1", "llama3.1"),
                            ("mixtral", "mixtral"),
                            ("text-embedding-ada-002", "text-embedding-ada-002"),
                        ],
                        default="gpt-4o-mini",
                        help_text="LLM to use in chat",
                        max_length=64,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("azure", "azure"),
                            ("bedrock", "bedrock"),
                            ("ollama", "ollama"),
                            ("open-ai", "open-ai"),
                            ("local-ai", "local-ai"),
                        ],
                        default="open-ai",
                        help_text="Backend to use in chat",
                        max_length=64,
                    ),
                ),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("general", "general"),
                            ("private", "private"),
                            ("disabled", "disabled"),
                        ],
                        default="general",
                        help_text="Availability of Model",
                        max_length=64,
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        choices=[("embedding", "embedding"), ("chat", "chat")],
                        default="chat",
                        help_text="The model type",
                        max_length=64,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="aisettings",
            name="chat_backend",
            field=models.CharField(
                choices=[
                    ("gpt-35-turbo-16k", "gpt-35-turbo-16k"),
                    ("gpt-4-turbo-2024-04-09", "gpt-4-turbo-2024-04-09"),
                    ("gpt-4o", "gpt-4o"),
                    ("gpt-4o-mini", "gpt-4o-mini"),
                    ("anthropic.claude-3-sonnet-20240229-v1:0", "claude-3-sonnet"),
                    ("anthropic.claude-3-haiku-20240307-v1:0", "claude-3-haiku"),
                    ("llama3.1", "llama3.1"),
                    ("mixtral", "mixtral"),
                    ("text-embedding-ada-002", "text-embedding-ada-002"),
                ],
                default="gpt-4o-mini",
                help_text="LLM to use in chat",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="chat_backend",
            field=models.CharField(
                choices=[
                    ("gpt-35-turbo-16k", "gpt-35-turbo-16k"),
                    ("gpt-4-turbo-2024-04-09", "gpt-4-turbo-2024-04-09"),
                    ("gpt-4o", "gpt-4o"),
                    ("gpt-4o-mini", "gpt-4o-mini"),
                    ("anthropic.claude-3-sonnet-20240229-v1:0", "claude-3-sonnet"),
                    ("anthropic.claude-3-haiku-20240307-v1:0", "claude-3-haiku"),
                    ("llama3.1", "llama3.1"),
                    ("mixtral", "mixtral"),
                    ("text-embedding-ada-002", "text-embedding-ada-002"),
                ],
                default="gpt-4o-mini",
                help_text="LLM to use in chat",
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="RegisteredModels",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("default", models.BooleanField(default=False)),
                (
                    "ai_settings",
                    models.ForeignKey(
                        default="default",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="registered_models",
                        to="redbox_core.aisettings",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        default="default",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="registered_aisettings",
                        to="redbox_core.mlmodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
