# Generated by Django 5.1.1 on 2024-10-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0046_chat_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accessibility_categories',
            field=models.CharField(blank=True, choices=[('Sight', "I'm blind, partially sighted or colour blind"), ('Hearing', "I'm deaf or hard of hearing"), ('Mobility', 'I have difficulty using a mouse or keyboard'), ('Thinking and understanding', 'I have autism, dyslexia, ADHD, a mental health condition'), ('Temporary', 'I have an injury'), ('Invisible condition', 'This could be menopause, a mental health condition')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='accessibility_description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='accessibility_options',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Prefer not to say', 'Prefer not to say')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='consent_agreement',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='consent_condfidentiality',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='consent_feedback',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='consent_interviews',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='consent_research',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='consent_understand',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='digital_confidence',
            field=models.CharField(blank=True, choices=[('I feel confident using new technologies and digital products', 'I feel confident using new technologies and digital products'), ('When using new technologies and digital products I tend to need some help', 'When using new technologies and digital products I tend to need some help'), ("I don't use new technologies and I don't want to learn how to use them", "I don't use new technologies and I don't want to learn how to use them")], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='how_useful',
            field=models.CharField(blank=True, choices=[('I have not used GenAI', 'I have not used GenAI'), ('I have not used GenAI enough to say its useful or not', 'I have not used GenAI enough to say its useful or not'), ('I have not figured out how to best use GenAI', 'I have not figured out how to best use GenAI'), ('I have found a few things GenAI really helps me with', 'I have found a few things GenAI really helps me with'), ('GenAI has proved useful for many different tasks', 'GenAI has proved useful for many different tasks')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role_duration_compare_multiple_docs',
            field=models.CharField(blank=True, choices=[('I do not do this task', 'I do not do this task'), ('1 to 15 minutes', '1 to 15 minutes'), ('15 to 60 minutes', '15 to 60 minutes'), ('1 to 4 hours', '1 to 4 hours'), ('4 to 8 hours', '4 to 8 hours'), ('1 to 2 days', '1 to 2 days'), ('More than 2 days', 'More than 2 days'), ('More than a week', 'More than a week')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role_duration_condense_multiple_docs',
            field=models.CharField(blank=True, choices=[('I do not do this task', 'I do not do this task'), ('1 to 15 minutes', '1 to 15 minutes'), ('15 to 60 minutes', '15 to 60 minutes'), ('1 to 4 hours', '1 to 4 hours'), ('4 to 8 hours', '4 to 8 hours'), ('1 to 2 days', '1 to 2 days'), ('More than 2 days', 'More than 2 days'), ('More than a week', 'More than a week')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role_duration_search_across_docs',
            field=models.CharField(blank=True, choices=[('I do not do this task', 'I do not do this task'), ('1 to 15 minutes', '1 to 15 minutes'), ('15 to 60 minutes', '15 to 60 minutes'), ('1 to 4 hours', '1 to 4 hours'), ('4 to 8 hours', '4 to 8 hours'), ('1 to 2 days', '1 to 2 days'), ('More than 2 days', 'More than 2 days'), ('More than a week', 'More than a week')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role_duration_shorten_docs',
            field=models.CharField(blank=True, choices=[('I do not do this task', 'I do not do this task'), ('1 to 15 minutes', '1 to 15 minutes'), ('15 to 60 minutes', '15 to 60 minutes'), ('1 to 4 hours', '1 to 4 hours'), ('4 to 8 hours', '4 to 8 hours'), ('1 to 2 days', '1 to 2 days'), ('More than 2 days', 'More than 2 days'), ('More than a week', 'More than a week')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role_duration_specific_template',
            field=models.CharField(blank=True, choices=[('I do not do this task', 'I do not do this task'), ('1 to 15 minutes', '1 to 15 minutes'), ('15 to 60 minutes', '15 to 60 minutes'), ('1 to 4 hours', '1 to 4 hours'), ('4 to 8 hours', '4 to 8 hours'), ('1 to 2 days', '1 to 2 days'), ('More than 2 days', 'More than 2 days'), ('More than a week', 'More than a week')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role_duration_summarise_large_docs',
            field=models.CharField(blank=True, choices=[('I do not do this task', 'I do not do this task'), ('1 to 15 minutes', '1 to 15 minutes'), ('15 to 60 minutes', '15 to 60 minutes'), ('1 to 4 hours', '1 to 4 hours'), ('4 to 8 hours', '4 to 8 hours'), ('1 to 2 days', '1 to 2 days'), ('More than 2 days', 'More than 2 days'), ('More than a week', 'More than a week')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role_duration_write_docs',
            field=models.CharField(blank=True, choices=[('I do not do this task', 'I do not do this task'), ('1 to 15 minutes', '1 to 15 minutes'), ('15 to 60 minutes', '15 to 60 minutes'), ('1 to 4 hours', '1 to 4 hours'), ('4 to 8 hours', '4 to 8 hours'), ('1 to 2 days', '1 to 2 days'), ('More than 2 days', 'More than 2 days'), ('More than a week', 'More than a week')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role_regularity_compare_multiple_docs',
            field=models.CharField(blank=True, choices=[('I do not do this task', 'I do not do this task'), ('Everyday', 'Everyday'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role_regularity_condense_multiple_docs',
            field=models.CharField(blank=True, choices=[('I do not do this task', 'I do not do this task'), ('Everyday', 'Everyday'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role_regularity_search_across_docs',
            field=models.CharField(blank=True, choices=[('I do not do this task', 'I do not do this task'), ('Everyday', 'Everyday'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role_regularity_shorten_docs',
            field=models.CharField(blank=True, choices=[('I do not do this task', 'I do not do this task'), ('Everyday', 'Everyday'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role_regularity_specific_template',
            field=models.CharField(blank=True, choices=[('I do not do this task', 'I do not do this task'), ('Everyday', 'Everyday'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role_regularity_summarise_large_docs',
            field=models.CharField(blank=True, choices=[('I do not do this task', 'I do not do this task'), ('Everyday', 'Everyday'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role_regularity_write_docs',
            field=models.CharField(blank=True, choices=[('I do not do this task', 'I do not do this task'), ('Everyday', 'Everyday'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='task_1_consider_using_ai',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Maybe (or unsure)', 'Maybe (or unsure)'), ('Yes', 'Yes'), ('Yes! I already use GenAI for this', 'Yes! I already use GenAI for this')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='task_1_description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='task_1_duration',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='task_1_regularity',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='task_2_consider_using_ai',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Maybe (or unsure)', 'Maybe (or unsure)'), ('Yes', 'Yes'), ('Yes! I already use GenAI for this', 'Yes! I already use GenAI for this')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='task_2_description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='task_2_duration',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='task_2_regularity',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='task_3_consider_using_ai',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Maybe (or unsure)', 'Maybe (or unsure)'), ('Yes', 'Yes'), ('Yes! I already use GenAI for this', 'Yes! I already use GenAI for this')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='task_3_description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='task_3_duration',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='task_3_regularity',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='usage_at_work',
            field=models.CharField(blank=True, choices=[('I have not used GenAI', 'I have not used GenAI'), ('Everyday', 'Everyday'), ('Weekly - a few times per week', 'Weekly - a few times per week'), ('Monthly - a few times per month', 'Monthly - a few times per month'), ('Not much at all - tried once or twice', 'Not much at all - tried once or twice')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='usage_outside_work',
            field=models.CharField(blank=True, choices=[('I have not used GenAI', 'I have not used GenAI'), ('Everyday', 'Everyday'), ('Weekly - a few times per week', 'Weekly - a few times per week'), ('Monthly - a few times per month', 'Monthly - a few times per month'), ('Not much at all - tried once or twice', 'Not much at all - tried once or twice')], max_length=64, null=True),
        ),
    ]
