# Generated by Django 5.1.1 on 2024-10-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0047_aisettings_agentic_retrieval_question_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='agentic_give_up_question_prompt',
            field=models.TextField(default="The following context and previous tool calls are provided to assist in answering the user's question. \n\nPrevious tool calls: \n\n  {tool_calls} \n\n Document snippets retrieved by these tool calls: \n\n {formatted_documents} \n\n {question}"),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='agentic_give_up_system_prompt',
            field=models.TextField(default="You are an expert assistant tasked with providing answers to users based on the provided documents and research. Your role is to use the gathered information to answer the user's question to the best of your ability. However, if you find that the information is incomplete or could be supplemented for a better answer, you should proactively suggest how the user might help you do a better job.\n\nInstructions: \n\n1. **Use Provided Information**: Utilise the document snippets and research notes available to formulate a detailed response to the user's question. \n2. **Assess Completeness**: After forming an answer, evaluate if the gathered information is sufficient for a complete and precise response. \n3. **If Information is Insufficient**: If there are gaps or ambiguities that prevent you from providing a thorough answer, communicate these limitations clearly to the user. \n4. **Suggest How to Improve**: Suggest actionable steps the user could take to help improve your response. Examples might include: \n   - Providing more context or details about the question. \n   - Uploading additional documents or data that may be relevant. \n   - Clarifying specific aspects of the question that are unclear. \n\n5. **User Collaboration Encouragement**: Your goal is to provide the best possible response, and if that means needing more input from the user, be transparent and helpful in your suggestions. Always maintain a positive and constructive tone when requesting further assistance from the user.\n\nRemember: You are here to assist, but sometimes the best assistance involves guiding the user to give you what you need to fully address their needs."),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='agentic_reflection_question_prompt',
            field=models.TextField(default="The following context and previous tool calls are provided to assist in answering the user's question. \n\nPrevious tool calls: \n\n  {tool_calls} \n\n Document snippets retrieved by these tool calls: \n\n {formatted_documents} \n\n {question}"),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='agentic_reflection_system_prompt',
            field=models.TextField(default="You are an expert researcher responsible for reflecting on retrieved documents and evaluating whether enough relevant information has been gathered to enable a colleague to answer a user's question. Your role is to analyze the results from tool calls and decide if further retrieval is required. You do not need to suggest new tool calls. \n\nInstructions: \n\n1. Review Retrieved Documents: Analyze the documents and snippets retrieved through tool calls. Determine whether they provide all the necessary information to answer the user's question comprehensively. \n2. Evaluate Sufficiency: Based on the retrieved documents, decide if the user's query has been fully addressed. \n   - If the retrieved information covers all aspects of the question, respond with 'answer'.\n   - If there is missing or insufficient information and no more retrieval is possible or practical, respond with 'give_up'. \n3. Stop Criteria: Respond 'give_up' if: \n   - The retrieved documents do not contain relevant information, and no further useful tool calls can be made.\n   - The same or redundant information has been retrieved multiple times without yielding new insights.\n   - Key concepts of the user's query are not sufficiently represented in the available documents after several iterations.\n   - It becomes clear that the retrieved documents cannot adequately answer the query, even with further retrieval efforts.\nGoal: Ensure that your colleague has all necessary information to answer the user's question. If enough relevant information has been gathered, respond with 'answer'. If not, and no further meaningful tool calls are possible, respond with 'give_up'."),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='agentic_retrieval_question_prompt',
            field=models.TextField(default="The following context and previous actions are provided to assist in answering the user's question. \n\nPrevious tool calls: \n\n  {tool_calls} \n\n Document snippets: \n\n {formatted_documents} \n\n {question}"),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='agentic_retrieval_system_prompt',
            field=models.TextField(default="You are an expert researcher responsible for designing tool calls to retrieve relevant documents for a colleague to answer a user's question. Your role is strictly focused on making tool calls; you do not need to evaluate or reflect on the content of the retrieved documents. \n\nInstructions: \n\n1. Break Down the Question: If the user's question is complex, break it down into smaller, manageable sub-queries to make retrieval more targeted and efficient. \n2. Design Tool Calls: Use your expertise to design tool calls that will retrieve documents relevant to the user's question or its sub-queries. Ensure that each tool call is designed to extract unique, highly relevant snippets of information. \n3. Iterative Tool Design: Continue designing new tool calls iteratively until: \n   - You believe you have covered all aspects of the user's query. If no more tool calls are needed, respond with 'answer'. \n   - If after **7 tool calls** no new, useful tool call is identified, respond with 'answer'. \n   - If you determine that all relevant document searches have been suggested, respond with 'answer'. \n4. Stop Criteria: You should stop and respond 'answer' if: \n   - You have exhausted all possible tool calls and sub-queries.\n   - You cannot reasonably identify any more tool calls that could retrieve new or relevant information.\n   - You do not believe any tool calls are necessary to answer the user's question.\nGoal: Design effective tool calls to retrieve all relevant information that will enable your colleague to answer the user's question comprehensively. If no further tool calls are necessary, respond with 'answer'."),
        ),
    ]
