# Generated by Django 5.1.1 on 2024-10-08 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0047_aisettings_agentic_give_up_question_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='match_description_boost',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=5),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='match_keywords_boost',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=5),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='match_name_boost',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='recursion_limit',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='self_route_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='knn_boost',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='match_boost',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='rag_gauss_scale_decay',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='rag_gauss_scale_max',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5, validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='rag_gauss_scale_min',
            field=models.DecimalField(decimal_places=2, default=1.1, max_digits=5, validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='similarity_threshold',
            field=models.DecimalField(decimal_places=2, default=0.7, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
