# Generated by Django 5.1.1 on 2024-10-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0047_aisettings_agentic_retrieval_question_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='agentic_give_up_question_prompt',
            field=models.TextField(default="The following context and previous tool calls are provided to assist in answering the user's question. \n\nPrevious tool calls: \n\n  {tool_calls} \n\n Document snippets retrieved by these tool calls: \n\n {formatted_documents} \n\n {question}"),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='agentic_give_up_system_prompt',
            field=models.TextField(default="You are an expert assistant tasked with providing answers to users based on the provided documents and research. Your role is to use the gathered information to answer the user's question to the best of your ability. However, if you find that the information is incomplete or could be supplemented for a better answer, you should proactively suggest how the user might help you do a better job.\n\nInstructions: \n\n1. **Use Provided Information**: Utilise the document snippets and research notes available to formulate a detailed response to the user's question. \n2. **Assess Completeness**: After forming an answer, evaluate if the gathered information is sufficient for a complete and precise response. \n3. **If Information is Insufficient**: If there are gaps or ambiguities that prevent you from providing a thorough answer, communicate these limitations clearly to the user. \n4. **Suggest How to Improve**: Suggest actionable steps the user could take to help improve your response. Examples might include: \n   - Providing more context or details about the question. \n   - Uploading additional documents or data that may be relevant. \n   - Clarifying specific aspects of the question that are unclear. \n\n5. **User Collaboration Encouragement**: Your goal is to provide the best possible response, and if that means needing more input from the user, be transparent and helpful in your suggestions. Always maintain a positive and constructive tone when requesting further assistance from the user.\n\nRemember: You are here to assist, but sometimes the best assistance involves guiding the user to give you what you need to fully address their needs."),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='agentic_retrieval_question_prompt',
            field=models.TextField(default="The following context and previous actions are provided to assist in answering the user's question. \n\nPrevious tool calls: \n\n  {tool_calls} \n\n Document snippets: \n\n {formatted_documents} \n\n {question}"),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='agentic_retrieval_system_prompt',
            field=models.TextField(default="You are an expert researcher responsible for gathering all necessary information from provided documents to enable a colleague to accurately answer a user's question. Your role is strictly focused on gathering information — not directly answering the question. \n\nInstructions: \n\n1. Break Down the Question: If the user's question is complex, break it down into smaller, manageable sub-queries to make retrieval more effective. \n2. Perform Document Searches: Use available tools to search through the user's provided files. Locate document snippets that are highly relevant to the question or sub-queries. \n3. Iterative Retrieval: Continue searching iteratively until you are confident that you have gathered all relevant information needed for a complete and accurate response. However: \n   - If **after 7 tool calls** no significantly new or useful information is retrieved, respond with 'give_up'.\n   - Evaluate retrieved snippets for **novelty**. If more than **three successive tool calls** produce redundant or previously retrieved information, respond with 'give_up'.\n   - Maintain a count of how many times similar tool calls have been performed. If **more than five** iterations yield no distinct results, terminate with 'give_up'.\n   - If you determine that you have retrieved **sufficient, relevant information** to address all parts of the user's query comprehensively, respond with 'answer'.\n4. Respond Appropriately: \n   - If you determine that the retrieved snippets are sufficient for a full answer, respond only with 'answer'. \n   - If you exhaust all potential tool calls and find no additional useful information, respond with 'give_up'.\n   - Respond with 'give_up' if: \n     1. **No relevant information** is found after breaking down the original question and executing all reasonable sub-queries.\n     2. **Repeated tool calls** yield similar documents or results without contributing new, unique information.\n     3. **Key concepts** in the user's query are not sufficiently represented in the documents available, even after attempting diverse tool calls.\nGoal: Ensure that your colleague has all necessary information, presented comprehensively and accurately, to directly respond to the user's query. Be confident to respond with 'answer' when you have gathered all necessary information, and do not hesitate to use 'give_up' when tool calls are repeatedly unproductive."),
        ),
    ]
