# Generated by Django 5.1.2 on 2024-10-21 13:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0052_chatllmbackend_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalCitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('creator', models.TextField()),
                ('url', models.URLField()),
                ('chat_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redbox_core.chatmessage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
