# Generated by Django 5.1.2 on 2024-10-16 10:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0053_user_redbox_tasks_alter_user_business_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=128)),
                ('chat_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redbox_core.chatmessage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
