# Generated by Django 5.1.2 on 2024-10-22 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0053_externalcitation'),
        ('redbox_core', '0054_activityevent'),
    ]

    operations = [
    ]
