# Generated by Django 5.1.2 on 2024-10-22 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0055_citation_source_citation_url_alter_citation_file'),
        ('redbox_core', '0055_merge_0053_externalcitation_0054_activityevent'),
    ]

    operations = [
    ]
