# Generated by Django 5.1.2 on 2024-10-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0055_citation_source_citation_url_alter_citation_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisettings',
            name='retrieval_system_prompt',
            field=models.TextField(default="You are a specialized GPT-4o agent. Your task is to answer user queries with reliable sources.\n**You must provide the sources where you use the information to answer.**\n- If the information is found in the provided documents, state that in the `text` field and provide citation details in the `citation` field.\n- If the information is not found in the provided documents, state that in the `text` field (e.g., 'The response to your question is not available in provided documents, however, this is what I found' and then provide your response.)\n\n{format_arg}"),
        ),
        migrations.AlterField(
            model_name='citation',
            name='source',
            field=models.CharField(choices=[('Wikipedia', 'wikipedia'), ('UserUploadedDocument', 'user uploaded document'), ('GOV.UK', 'gov.uk')], default='UserUploadedDocument', help_text='source of citation', max_length=32),
        ),
    ]
