# Generated by Django 5.1.2 on 2024-10-22 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0056_merge_20241022_1437'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExternalCitation',
        ),
    ]
