# Generated by Django 5.1.2 on 2024-10-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0056_alter_aisettings_retrieval_system_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='text_in_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
