# Generated by Django 5.1.2 on 2024-10-24 08:31

import redbox_app.redbox_core.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0056_alter_aisettings_retrieval_system_prompt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='original_file',
            field=models.FileField(storage=storages.backends.s3.S3Storage, upload_to=redbox_app.redbox_core.models.user_directory_path),
        ),
        migrations.RenameField(
            model_name='file',
            old_name='original_file_name',
            new_name='old_file_name',
        ),
    ]
