# Generated by Django 5.1.2 on 2024-10-24 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0056_alter_file_original_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='original_file_name',
            new_name='old_file_name',
        ),
    ]
