# Generated by Django 5.1.2 on 2024-10-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0057_citation_text_in_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='source',
            field=models.CharField(choices=[('Wikipedia', 'wikipedia'), ('UserUploadedDocument', 'user uploaded document'), ('Gov.Uk', 'gov.uk')], default='UserUploadedDocument', help_text='source of citation', max_length=32),
        ),
    ]
