# Generated by Django 5.1.2 on 2024-11-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0058_alter_file_original_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisettings',
            name='retrieval_system_prompt',
            field=models.TextField(default='You are a specialized GPT-4o agent. Your task is to answer user queries with reliable sources.\n**You must provide the citations where you use the information to answer.**\n\n{format_arg}'),
        ),
    ]
