# Generated by Django 5.1.2 on 2024-10-31 15:31

from django.db import migrations, models
from django.db.models import Max


def delete_duplicate_files(apps, schema_editor):
    File = apps.get_model("redbox_core", "File")

    latest_files = File.objects.values('original_file', 'user').annotate(latest_created_at=Max('created_at'))

    # Get the list of ids to keep based on latest_created_at
    ids_to_keep = [
        File.objects.get(original_file=doc['original_file'], user=doc['user'], created_at=doc['latest_created_at']).id
        for doc in latest_files
    ]

    # Delete all other documents
    File.objects.exclude(id__in=ids_to_keep).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0058_alter_file_original_file'),
    ]

    operations = [
        # migrations.RunPython(delete_duplicate_files, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(fields=('original_file', 'user'), name='unique user-file'),
        ),
    ]
