# Generated by Django 5.1.2 on 2024-10-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0058_alter_file_original_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='text_in_answer',
            field=models.TextField(blank=True, help_text='the part of the answer the citation refers too - useful for adding in footnotes', null=True),
        ),
    ]
