# Generated by Django 5.1.2 on 2024-10-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0058_alter_aisettings_retrieval_system_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='source',
            field=models.CharField(choices=[('Wikipedia', 'wikipedia'), ('UserUploadedDocument', 'user uploaded document'), ('GOV.UK', 'gov.uk')], default='UserUploadedDocument', help_text='source of citation', max_length=32),
        ),
    ]
