# Generated by Django 5.1.2 on 2024-10-29 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0058_alter_citation_source'),
        ('redbox_core', '0058_alter_file_original_file'),
    ]
