# Generated by Django 5.1.2 on 2024-10-31 13:36
from django.db.models import Max

import redbox_app.redbox_core.models
import storages.backends.s3
from django.db import migrations, models


def delete_duplicate_files(apps, schema_editor):
    File = apps.get_model("redbox_core", "File")

    latest_files = File.objects.values('original_file').annotate(latest_created_at=Max('created_at'))

    # Get the list of ids to keep based on latest_created_at
    ids_to_keep = [
        File.objects.get(original_file=doc['original_file'], created_at=doc['latest_created_at']).id
        for doc in latest_files
    ]

    # Delete all other documents
    File.objects.exclude(id__in=ids_to_keep).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0058_alter_file_original_file'),
    ]

    operations = [
        migrations.RunPython(delete_duplicate_files, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='file',
            name='original_file',
            field=models.FileField(storage=storages.backends.s3.S3Storage, unique=True, upload_to=redbox_app.redbox_core.models.build_s3_key),
        ),
    ]
