# Generated by Django 5.1.2 on 2024-11-01 07:25

import redbox_app.redbox_core.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0059_delete_duplicate_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='original_file',
            field=models.FileField(storage=storages.backends.s3.S3Storage, unique=True, upload_to=redbox_app.redbox_core.models.build_s3_key),
        ),
    ]
