# Generated by Django 5.1.2 on 2024-11-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0060_remove_user_invite_accepted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='text_in_answer',
            field=models.TextField(blank=True, help_text='the part of the answer the citation refers too - useful for adding in footnotes', null=True),
        ),
    ]
