# Generated by Django 5.1.2 on 2024-11-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0061_alter_citation_text_in_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisettings',
            name='retrieval_system_prompt',
            field=models.TextField(default='You are a specialized GPT-4o agent. Your task is to answer user queries with reliable sources.\n**You must provide the citations where you use the information to answer.**\nUse the `creator_type` as `source_type` if available.\n\n{format_arg}'),
        ),
    ]
