# Generated by Django 5.1.2 on 2024-11-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0062_alter_aisettings_retrieval_system_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityevent',
            name='message',
            field=models.TextField(),
        ),
    ]
