# Generated by Django 5.1.2 on 2024-11-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0064_alter_aisettings_retrieval_system_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisettings',
            name='chat_map_system_prompt',
            field=models.TextField(default='Your goal is to extract the most important information and present it in a concise and coherent manner. Please follow these guidelines while summarizing: \n1) Identify and highlight key points,\n2) Avoid repetition,\n3) Ensure the summary is easy to understand,\n4) Maintain the original context and meaning.\n'),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='chat_system_prompt',
            field=models.TextField(default='You are tasked with providing information objectively and responding helpfully to users'),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='chat_with_docs_reduce_system_prompt',
            field=models.TextField(default='You are tasked with answering questions on user provided documents. Your goal is to answer the user question based on list of summaries in a coherent manner.Please follow these guidelines while answering the question: \n1) Identify and highlight key points,\n2) Avoid repetition,\n3) Ensure the answer is easy to understand,\n4) Maintain the original context and meaning.\n'),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='chat_with_docs_system_prompt',
            field=models.TextField(default='You are tasked with providing information objectively and responding helpfully to users using context from their provided documents'),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='reduce_system_prompt',
            field=models.TextField(default='Your goal is to write a concise summary of list of summaries from a list of summaries in a concise and coherent manner. Please follow these guidelines while summarizing: \n1) Identify and highlight key points,\n2) Avoid repetition,\n3) Ensure the summary is easy to understand,\n4) Maintain the original context and meaning.\n'),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='retrieval_system_prompt',
            field=models.TextField(default='Your task is to answer user queries with reliable sources.\n**You must provide the citations where you use the information to answer.**\nUse UK English spelling in response.\nUse the document `creator_type` as `source_type` if available.\n\n'),
        ),
    ]
