# Generated by Django 5.1.2 on 2024-11-12 06:09

from django.db import migrations, models

def set_ai_settings_prompt_value_to_null(apps, schema_editor):
    AISettings = apps.get_model("redbox_core", "AISettings")
    for ai_settings in AISettings.objects.all():
        ai_settings.chat_system_prompt = None
        ai_settings.chat_question_prompt = None
        ai_settings.chat_with_docs_system_prompt = None
        ai_settings.chat_with_docs_question_prompt = None
        ai_settings.chat_with_docs_reduce_system_prompt = None
        ai_settings.retrieval_system_prompt = None
        ai_settings.retrieval_question_prompt = None
        ai_settings.agentic_retrieval_system_prompt = None
        ai_settings.agentic_retrieval_question_prompt = None
        ai_settings.agentic_give_up_system_prompt = None
        ai_settings.agentic_give_up_question_prompt = None
        ai_settings.condense_system_prompt = None
        ai_settings.condense_question_prompt = None
        ai_settings.chat_map_system_prompt = None
        ai_settings.chat_map_question_prompt = None
        ai_settings.reduce_system_prompt = None
        ai_settings.save()

class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0066_alter_aisettings_agentic_retrieval_system_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisettings',
            name='agentic_give_up_question_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='agentic_give_up_system_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='agentic_retrieval_question_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='agentic_retrieval_system_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='chat_map_question_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='chat_map_system_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='chat_question_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='chat_system_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='chat_with_docs_question_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='chat_with_docs_reduce_system_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='chat_with_docs_system_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='condense_question_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='condense_system_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='reduce_system_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='retrieval_question_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='retrieval_system_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunPython(back_populate_ai_settings_chat_backend, migrations.RunPython.noop),

    ]
