# Generated by Django 5.1.2 on 2024-11-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0067_alter_aisettings_agentic_give_up_question_prompt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='how_useful',
            field=models.CharField(blank=True, choices=[('I have not used GenAI', 'I have not used GenAI'), ("I have not used GenAI enough to say if it's useful or not", "I have not used GenAI enough to say if it's useful or not"), ('I have not figured out how to best use GenAI', 'I have not figured out how to best use GenAI'), ('I have found a few things GenAI really helps me with', 'I have found a few things GenAI really helps me with'), ('GenAI has proved useful for many different tasks', 'GenAI has proved useful for many different tasks')], max_length=64, null=True),
        ),
    ]
