# Generated by Django 5.1.2 on 2024-11-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0068_alter_user_how_useful'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='source',
            field=models.CharField(blank=True, choices=[('Wikipedia', 'wikipedia'), ('UserUploadedDocument', 'user uploaded document'), ('GOV.UK', 'gov.uk')], default='UserUploadedDocument', help_text='source of citation', max_length=32, null=True),
        ),
    ]
