# Generated by Django 5.1.2 on 2024-12-03 07:09
from datetime import datetime

from django.db import migrations, models


def back_fill_user_dates(apps, schema_editor):
    User = apps.get_model("redbox_core", "User")
    now = datetime.now()
    User.objects.update(created_at=now, modified_at=now)


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0069_alter_citation_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.RunPython(back_fill_user_dates, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
