# Generated by Django 5.1.4 on 2024-12-12 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0069_alter_citation_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='chat',
            field=models.ForeignKey(blank=True, help_text='chat that this document belongs to, which may be nothing for now', null=True, on_delete=django.db.models.deletion.CASCADE, to='redbox_core.chat'),
        ),
    ]
