# Generated by Django 5.1.3 on 2024-11-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redbox_core", "0069_alter_citation_source"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
