# Generated by Django 5.1.4 on 2024-12-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0070_file_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='metadata',
            field=models.JSONField(blank=True, help_text='metadata extracted from file', null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='text',
            field=models.TextField(blank=True, help_text='text extracted from file', null=True),
        ),
    ]
