# Generated by Django 5.1.3 on 2025-01-07 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0071_file_metadata_file_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityEvent',
        ),
    ]
