# Generated by Django 5.1.3 on 2025-01-07 13:37

from django.db import migrations, models

def back_populate_new_source_files(apps, schema_editor):
    ChatMessage = apps.get_model("redbox_core", "ChatMessage")
    for chat_message in ChatMessage.objects.all():
        for source_file in chat_message.source_files.all():
            chat_message.new_source_files.add(source_file)


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0072_delete_activityevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='new_source_files',
            field=models.ManyToManyField(related_name='source_files', to='redbox_core.file'),
        ),
        migrations.RunPython(back_populate_new_source_files, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='chatmessage',
            name='source_files',
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='new_source_files',
            new_name='source_files',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='source_files',
            field=models.ManyToManyField(related_name='+', to='redbox_core.file'),
        ),
    ]
