# Generated by Django 5.1.3 on 2025-01-07 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0073_chatmessage_new_source_files'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Citation',
        ),
    ]
