# Generated by Django 5.1.3 on 2025-01-09 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0074_delete_citation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='source_files',
        ),
    ]
