# Generated by Django 5.1.3 on 2025-01-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0074_delete_citation'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='token_count',
            field=models.PositiveIntegerField(blank=True, help_text='number of tokens in the message', null=True),
        ),
    ]
