# Generated by Django 5.1.3 on 2025-01-15 06:56

from django.db import migrations, models

def back_populate_token_count(apps, schema_editor):
    ChatMessage = apps.get_model("redbox_core", "ChatMessage")
    for chat_message in ChatMessage.objects.all():
        chat_message.save()


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0074_delete_citation'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='token_count',
            field=models.PositiveIntegerField(blank=True, help_text='number of tokens in the message', null=True),
        ),
        migrations.RunPython(back_populate_token_count, migrations.RunPython.noop),
    ]
