# Generated by Django 5.1.3 on 2025-01-20 11:05

from django.db import migrations, models

def delete_deleted_files(apps, schema_editor):
    File = apps.get_model("redbox_core", "File")
    File.objects.filter(status="deleted").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0075_chatmessage_token_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='original_file_name',
        ),
        migrations.RunPython(delete_deleted_files, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='file',
            name='status',
            field=models.CharField(
                choices=[('complete', 'Complete'), ('errored', 'Errored'), ('processing', 'Processing')]),
        ),

    ]
