# Generated by Django 5.1.3 on 2025-01-16 13:23

from django.db import migrations, models

def back_populate_file_token_count(apps, schema_editor):
    File = apps.get_model("redbox_core", "File")
    for file in File.objects.filter(metadata__isnull=False):
        file.token_count = file.metadata.get("token_count")
        file.save()


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0076_remove_file_original_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='token_count',
            field=models.PositiveIntegerField(blank=True, help_text='number of tokens in the document', null=True),
        ),
        migrations.RunPython(back_populate_file_token_count, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='file',
            name='metadata',
        ),
    ]
