# Generated by Django 5.1.3 on 2025-01-21 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_q', '0018_task_success_index'),
        ('redbox_core', '0076_remove_file_original_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_q.ormq'),
        ),
    ]
