# Generated by Django 5.1.3 on 2025-01-16 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0076_remove_file_original_file_name_file_token_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessageTokenUse',
        ),
    ]
