# Generated by Django 5.1.3 on 2025-01-22 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_q', '0018_task_success_index'),
        ('redbox_core', '0078_alter_file_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='task',
            field=models.ForeignKey(blank=True, help_text='pending text extraction task', null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_q.ormq'),
        ),
    ]
