# Generated by Django 5.1.3 on 2025-01-22 14:19

from django.db import migrations, models

def back_populate_file_token_count(apps, schema_editor):
    File = apps.get_model("redbox_core", "File")
    for file in File.objects.filter(metadata__isnull=False):
        file.token_count = file.metadata.get("token_count")
        file.save()

class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0079_alter_file_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='token_count',
            field=models.PositiveIntegerField(blank=True, help_text='number of tokens in extracted text', null=True),
        ),
        migrations.RunPython(back_populate_file_token_count, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='file',
            name='metadata',
        ),
        migrations.DeleteModel(
            name='ChatMessageTokenUse',
        ),
    ]
