# Generated by Django 5.1.5 on 2025-01-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0080_file_token_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ai_settings',
        ),
        migrations.AddField(
            model_name='chatllmbackend',
            name='context_window_size',
            field=models.PositiveIntegerField(blank=True, help_text='size of the LLM  context window', null=True),
        ),
        migrations.DeleteModel(
            name='AISettings',
        ),
    ]
