# Generated by Django 5.1.5 on 2025-01-27 15:36
import django
from django.db import migrations, models


def remove_files_without_chat(apps, schema_editor):
    File = apps.get_model("redbox_core", "File")
    File.objects.filter(chat__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0081_remove_user_ai_settings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='selected_files',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='source_files',
        ),
        migrations.RunPython(remove_files_without_chat, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='file',
            name='chat',
            field=models.ForeignKey(help_text='chat that this document belongs to, which may be nothing for now',
                                    on_delete=django.db.models.deletion.CASCADE, to='redbox_core.chat'),
        ),

    ]
