# Generated by Django 5.1.5 on 2025-01-28 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0081_remove_user_ai_settings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='selected_files',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='source_files',
        ),
    ]
