# Generated by Django 5.1.5 on 2025-01-30 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0082_remove_chatmessage_selected_files_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='user',
        ),
    ]
