# Generated by Django 5.1.5 on 2025-01-30 13:56

import django.db.models.deletion
from django.db import migrations, models

def kill_orphans(apps, schema_editor):
    File = apps.get_model("redbox_core", "File")
    File.objects.filter(chat__isnull=True).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0082_remove_chatmessage_selected_files_and_more'),
    ]

    operations = [
        migrations.RunPython(kill_orphans, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='file',
            name='user',
        ),
        migrations.AlterField(
            model_name='file',
            name='chat',
            field=models.ForeignKey(help_text='chat that this document belongs to, which may be nothing for now', on_delete=django.db.models.deletion.CASCADE, to='redbox_core.chat'),
        ),
    ]
