# Generated by Django 5.1.5 on 2025-02-04 09:06

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0083_remove_file_user'),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='TextChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=3072)),
                ('text', models.TextField()),
                ('index', models.PositiveIntegerField()),
                ('token_count', models.PositiveIntegerField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redbox_core.file')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
