# Generated by Django 5.1.5 on 2025-02-05 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0083_remove_file_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='route',
        ),
    ]
