# Generated by Django 5.1.5 on 2025-02-06 09:32

from django.db import migrations, models


rate_limits = {
    "gpt-4o-mini": 2000000,
    "gpt-4o": 1000000,
    "gpt-35-turbo-16k": 300000,
    "gpt-4-turbo-2024-04-09": 150000,
    "gpt-4o-2024-08-06": 2000000
}

def back_populate_rate_limit(apps, schema_editor):
    ChatLLMBackend = apps.get_model("redbox_core", "ChatLLMBackend")
    for llm in ChatLLMBackend.objects.all():
        llm.rate_limit = rate_limits.get(llm.name, 1000000)
        llm.save()

def back_populate_chat_message_delays(apps, schema_editor):
    ChatMessage = apps.get_model("redbox_core", "ChatMessage")
    ChatMessage.objects.all().update(delay=0)

class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0084_remove_chatmessage_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatllmbackend',
            name='rate_limit',
            field=models.PositiveIntegerField(blank=True, help_text='tokens per minute allowed by this model', null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='delay',
            field=models.FloatField(blank=True, default=0, help_text='by how much was this message delayed in seconds',
                                    null=True),
        ),
        migrations.RunPython(back_populate_rate_limit, migrations.RunPython.noop),
        migrations.RunPython(back_populate_chat_message_delays, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='chatllmbackend',
            name='rate_limit',
            field=models.PositiveIntegerField(default=1000000, help_text='tokens per minute allowed by this model'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='delay',
            field=models.FloatField(default=0, help_text='by how much was this message delayed in seconds'),
        ),
    ]
