# Generated by Django 5.1.5 on 2025-02-13 09:10

import django.db.models.deletion
from django.db import migrations, models

def delete_orphans(apps, schema_editor):
    File = apps.get_model("redbox_core", "File")
    File.objects.filter(chat__isnull=True).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0086_alter_user_business_unit'),
    ]

    operations = [
        migrations.RunPython(delete_orphans, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='file',
            name='chat',
            field=models.ForeignKey(help_text='chat that this document belongs to, which may be nothing for now', on_delete=django.db.models.deletion.CASCADE, to='redbox_core.chat'),
        ),
    ]
