# Generated by Django 5.1.5 on 2025-02-13 16:21
from datetime import datetime

from django.db import migrations, models
from pytz import utc


def back_populate_dates(apps, schema_editor):
    User = apps.get_model("redbox_core", "User")
    now = datetime.now(tz=utc)
    User.objects.filter(created_at__isnull=True).update(created_at=now)
    User.objects.filter(modified_at__isnull=True).update(modified_at=now)


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0087_alter_file_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.RunPython(back_populate_dates, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['created_at']},
        ),
    ]
