# Generated by Django 5.1.5 on 2025-02-20 16:28

import django.db.models.deletion
import uuid
from django.db import migrations, models

def back_populate_department_business_unit(apps, schema_editor):
    DepartmentBusinessUnit = apps.get_model("redbox_core", "DepartmentBusinessUnit")
    for business_unit in [
        "Borders Unit",
        "Central Costs",
        "Central Digital and Data Office",
        "Civil Service Commission",
        "Civil Service Human Resources",
        "CO Chief Operating Officer",
        "CO Digital",
        "CO HMT Commercial",
        "CO People and Places",
        "CO Strategy, Finance, and Performance",
        "Commercial Models",
        "COP Presidency",
        "Covid Inquiry",
        "Crown Commercial Service",
        "CS Modernisation and Reform Unit",
        "Delivery Group",
        "Economic and Domestic Secretariat",
        "Equality and Human Rights Commission",
        "Equality Hub",
        "Flexible CS Pool",
        "Geospatial Commission",
        "Government Business Services",
        "Government Commercial and Grants Function",
        "Government Communication Service",
        "Government Digital Service",
        "Government in Parliament",
        "Government Legal Department",
        "Government People Group",
        "Government Property Agency",
        "Government Security Group",
        "Grenfell Inquiry",
        "Infected Blood Inquiry",
        "Infrastructure and Projects Authority",
        "Inquiries Sponsorship Team",
        "Intelligence and Security Committee",
        "Joint Intelligence Organisation",
        "National Security Secretariat",
        "Office for Veterans' Affairs",
        "Office of Government Property",
        "Office of the Registrar of Consultant Lobbyists",
        "Prime Minister's Office",
        "Propriety and Constitution Group",
        "Public Bodies and Priority Projects Unit",
        "Public Inquiry Response Unit",
        "Public Sector Fraud Authority",
        "UKSV",
        "Union and Constitution Group",
        "Other",
    ]:
        DepartmentBusinessUnit.objects.create(department="Cabinet Office", business_unit=business_unit)

    for business_unit in [
        "DSIT Data Science & Data Transformation",
        "DSIT Media & Digital",
        "DSIT Strategic Engagement",
        "DSIT Strategy, Planning & Insights",
        "DSIT Transformation",
        "DSIT Telecommunications Policy",
        "DSIT AI Policy Analysis",
        "DSIT AI Security Institute",
        "DSIT Transformation & Innovation Directorate",
        "DSIT AI Regulation",
        "DSIT Project Delivery Profession",
        "DSIT Expert Exchange Programme",
        "Other",
    ]:
        DepartmentBusinessUnit.objects.create(
            department="Department for Science, Innovation & Technology", business_unit=business_unit
        )

    DepartmentBusinessUnit.objects.create(
        department="Department for Science, Innovation & Technology", business_unit=business_unit
    )

    User = apps.get_model("redbox_core", "User")
    for user in User.objects.all():
        try:
            user.new_business_unit = DepartmentBusinessUnit.objects.get(business_unit=user.business_unit)
        except DepartmentBusinessUnit.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0089_alter_user_business_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentBusinessUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('department', models.CharField(choices=[('Number 10', 'Number 10'), ('Cabinet Office', 'Cabinet Office'), ('Department for Science, Innovation & Technology', 'Department for Science, Innovation & Technology'), ('Other Department', 'Other Department')], default='Other Department', help_text='Government department', max_length=64)),
                ('business_unit', models.CharField(help_text='Business Unit', max_length=128)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='new_business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='redbox_core.departmentbusinessunit'),
        ),
        migrations.RunPython(back_populate_department_business_unit, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='user',
            name='business_unit',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='new_business_unit',
            new_name='business_unit',
        ),

    ]
