# Generated by Django 5.1.5 on 2025-02-20 16:28

import django.db.models.deletion
import uuid
from django.db import migrations, models
from django.db.models import Count


def back_populate_department_business_unit(apps, schema_editor):
    DepartmentBusinessUnit = apps.get_model("redbox_core", "DepartmentBusinessUnit")
    DepartmentBusinessUnit.objects.all().delete()

    User = apps.get_model("redbox_core", "User")
    for user in User.objects.all():
        department = "Department for Science, Innovation & Technology" if user.business_unit.startswith("DSIT") else "Cabinet Office"
        business_unit, _ = DepartmentBusinessUnit.objects.get_or_create(department=department,
                                                                     business_unit=user.business_unit)


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0089_alter_user_business_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentBusinessUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('department', models.CharField(choices=[('Number 10', 'Number 10'), ('Cabinet Office', 'Cabinet Office'), ('Department for Science, Innovation & Technology', 'Department for Science, Innovation & Technology'), ('Other Department', 'Other Department')], default='Other Department', help_text='Government department', max_length=64)),
                ('business_unit', models.CharField(help_text='Business Unit', max_length=128)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='new_business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='redbox_core.departmentbusinessunit'),
        ),
        migrations.RunPython(back_populate_department_business_unit, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='business_unit',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.RenameField(
            model_name='user',
            old_name='business_unit',
            new_name='old_business_unit',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='new_business_unit',
            new_name='business_unit',
        ),
    ]
