# Generated by Django 5.1.5 on 2025-02-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0090_departmentbusinessunit_user_new_business_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentbusinessunit',
            options={},
        ),
        migrations.AddConstraint(
            model_name='departmentbusinessunit',
            constraint=models.UniqueConstraint(fields=('department', 'business_unit'), name='department-business_unit-unique'),
        ),
    ]
