# Generated by Django 5.1.5 on 2025-02-26 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0091_alter_departmentbusinessunit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='business_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redbox_core.departmentbusinessunit'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='old_business_unit',
        ),
    ]
