# Generated by Django 5.1.5 on 2025-02-26 09:18

from django.db import migrations


def back_populate_department_business_unit(apps, schema_editor):
    DepartmentBusinessUnit = apps.get_model("redbox_core", "DepartmentBusinessUnit")

    User = apps.get_model("redbox_core", "User")

    cabinet_office, _ = DepartmentBusinessUnit.objects.get_or_create(
        department="Cabinet Office",
        business_unit="Other",
    )
    User.objects.filter(business_unit__department="Other Department", email__endswith="cabinetoffice.gov.uk").update(business_unit=cabinet_office)



class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0091_alter_departmentbusinessunit_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='old_business_unit',
        ),
        migrations.RunPython(back_populate_department_business_unit, migrations.RunPython.noop),
    ]
