# Generated by Django 5.1.6 on 2025-03-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0092_remove_user_old_business_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='time_to_first_token',
            field=models.DurationField(blank=True, help_text='time take to for LLM to respond with first token', null=True),
        ),
    ]
