# Generated by Django 5.1.7 on 2025-06-27 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0093_chatmessage_time_to_first_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='temperature',
            field=models.FloatField(default=0, help_text='temperature for LLM', validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
    ]
