# Generated by Django 5.0.6 on 2024-05-16 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0006_file_core_file_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chathistory',
            options={'verbose_name_plural': 'Chat history'},
        ),
    ]
