# Generated by Django 5.0.6 on 2024-05-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("redbox_core", "0008_alter_file_processing_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="expiry_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
