# Generated by Django 5.0.6 on 2024-05-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("redbox_core", "0010_rename_expiry_date_file_last_referenced"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("uploaded", "Uploaded"),
                    ("parsing", "Parsing"),
                    ("chunking", "Chunking"),
                    ("embedding", "Embedding"),
                    ("indexing", "Indexing"),
                    ("complete", "Complete"),
                    ("unknown", "Unknown"),
                    ("deleted", "Deleted"),
                ]
            ),
        ),
        migrations.RenameField(
            model_name="file",
            old_name="processing_status",
            new_name="status",
        ),
    ]
