# Generated by Django 5.0.6 on 2024-06-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0012_alter_file_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='selected_files',
            field=models.ManyToManyField(blank=True, related_name='+', to='redbox_core.file'),
        ),
    ]
