# Generated by Django 5.0.6 on 2024-06-07 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0013_chatmessage_selected_files_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chathistory',
            name='selected_files',
        ),
    ]
