# Generated by Django 5.0.6 on 2024-06-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0017_alter_user_business_unit_alter_user_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='route',
            field=models.CharField(blank=True, choices=[('info', 'Info'), ('ability', 'Ability'), ('coach', 'Coach'), ('gratitude', 'Gratitude'), ('retrieval', 'Retrieval'), ('summarisation', 'Summarisation'), ('extract', 'Extract'), ('vanilla', 'Vanilla')], null=True),
        ),
    ]
