# Generated by Django 5.0.6 on 2024-06-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0018_chatmessage_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='route',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
