# Generated by Django 5.0.7 on 2024-07-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0023_citation_page_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ai_experience',
            field=models.CharField(blank=True, choices=[('Curious Newcomer', "I haven't used Generative AI tools"), ('Cautious Explorer', 'I have a little experience using Generative AI tools'), ('Enthusiastic Experimenter', 'I occasionally use Generative AI tools but am still experimenting with their capabilities'), ('Experienced Navigator', 'I use Generative AI tools regularly and have a good understanding of their strengths and limitations'), ('AI Alchemist', 'I have extensive experience with Generative AI tools and can leverage them effectively in various contexts')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
